apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: site
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Minha Página NGINX</title>
    </head>
    <body>
        <h1>Olá, mundo do Kubernetes!</h1>
        <p>Servido pelo NGINX com ConfigMap 💡</p>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: site  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: nginx-html

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: site  
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
